language: node_js
node_js:
  - 8
install:
  - npm install
  - npm install -g codecov
script:
  - npm run lint
  - npm run format:check
  - npm run test:coverage
  - codecov
cache:
  directories:
    - "node_modules"
