export { default as formatHour } from './formatHour';
export { default as isDaytime } from './isDaytime';
export { default as normalizeCities } from './normalizeCities';
export { default as normalizeCurrentWeather } from './normalizeCurrentWeather';
export { default as normalizeFiveDayForecast } from './normalizeFiveDayForecast';
export { default as removeDecimals } from './removeDecimals';
export { default as shortDate } from './removeDecimals';
export { default as weekday } from './weekday';
export { default as delay } from './delay';
